P062constraintlayoutmodule
SteblinaTetiana/Android-Course-Home-Works pull request #1
Opened 2021-10-31 20:09 UTC by SteblinaTetiana

Please check my feature, the task is completely done.

2021-11-04 18:53 UTC, AlexMarikutsa requested changes

2021-11-04 18:53 UTC, AlexMarikutsa commented on p062ConstraintLayout/src/main/res/layout/activity_main.xml
> +        android:id="@+id/imgAndroidStudio"
imgAndroidStudio - погана назва. Назва має говорити про те,що це за в'ю

2021-11-07 16:08 UTC, SteblinaTetiana commented on p062ConstraintLayout/src/main/res/layout/activity_main.xml
> +        android:id="@+id/imgAndroidStudio"
Тобто прописувати повністю назву - imageAndroidStudio?

2021-11-12 13:33 UTC, AlexMarikutsa commented on p062ConstraintLayout/src/main/res/layout/activity_main.xml
> +        android:id="@+id/imgAndroidStudio"
Ні. Наприклад "name", "avatar", "age"...

2021-11-12 13:33 UTC, closed without merging